//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDANGKY
    {
        public int MaDon { get; set; }
        public Nullable<int> MaSV { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
