//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string CongViec { get; set; }
        public Nullable<decimal> LuongThang { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
    }
}
