//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIKTX
    {
        public string MaBienLai { get; set; }
        public Nullable<int> MaSV { get; set; }
        public Nullable<decimal> TienPhong { get; set; }
        public Nullable<decimal> TienInternet { get; set; }
        public Nullable<decimal> TienDien { get; set; }
        public Nullable<decimal> TienGuiXe { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public System.DateTime NgayDong { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
