//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGKYTUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGKYTUC()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
            this.TRANGTHIETBIs = new HashSet<TRANGTHIETBI>();
        }
    
        public string MaPhong { get; set; }
        public Nullable<int> MaQL { get; set; }
        public Nullable<int> SoGiuong { get; set; }
        public Nullable<int> SoSV { get; set; }
        public string TinhTrangPhong { get; set; }
    
        public virtual QUANLY QUANLY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHIETBI> TRANGTHIETBIs { get; set; }
    }
}
