//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.DONDANGKies = new HashSet<DONDANGKY>();
            this.NGUOITHANs = new HashSet<NGUOITHAN>();
            this.PHIKTXes = new HashSet<PHIKTX>();
        }
    
        public int MaSV { get; set; }
        public string HoTenSV { get; set; }
        public string GioiTinh { get; set; }
        public string SoDT { get; set; }
        public string SoCCCD { get; set; }
        public System.DateTime NgayVao { get; set; }
        public Nullable<System.DateTime> NgayRa { get; set; }
        public string MaPhong { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public Nullable<System.DateTime> NgayCoc { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDANGKY> DONDANGKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOITHAN> NGUOITHANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIKTX> PHIKTXes { get; set; }
        public virtual PHONGKYTUC PHONGKYTUC { get; set; }
        public override string ToString()
        {
            return MaSV.ToString();
        }
    }
}
