//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIGIANTHAM
    {
        public string MaTG { get; set; }
        public System.DateTime ThoiGianVao { get; set; }
        public System.DateTime ThoiGianRa { get; set; }
        public string MaNT { get; set; }
    
        public virtual NGUOITHAN NGUOITHAN { get; set; }
    }
}
