//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHIETBI
    {
        public string MaTB { get; set; }
        public string TenTB { get; set; }
        public string MaPhong { get; set; }
    
        public virtual PHONGKYTUC PHONGKYTUC { get; set; }
    }
}
